FROM node:12.16.1

WORKDIR /var/www/
COPY web/ .

RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build:prod

FROM nginx:alpine

COPY .docker-compose/nginx/conf.d/my.conf /etc/nginx/conf.d/my.conf
COPY --from=0 /var/www/dist /usr/share/nginx/html
RUN cat /etc/nginx/nginx.conf
RUN cat /etc/nginx/conf.d/my.conf
RUN ls -al /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

CMD ls -al /usr/share/nginx/html
