FROM node:12.16.1

WORKDIR /var/www/
COPY server/ .

RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build

FROM node:12.16.1

COPY --from=0 /var/www/dist /var/www/
COPY --from=0 /var/www/node_modules /var/www/node_modules
COPY --from=0 /var/www/package.json /var/www/package.json

WORKDIR /var/www/

CMD npm run serve
